stages:
    - build
    - test
    - deploy
build:
    stage: build
    script: 
        - echo "Building"
        - mkdir build
        - echo "hello" > build/info.txt
    artifacts: 
        paths:
            - build/
test:
    stage: test
    script: 
        - echo "Testing"
        - mkdir test
        - test -f "build/info.txt"
    when: manual
    artifacts:
        paths:
            - test
deploy:
    stage: deploy
    script:
        - echo "Deployment is succesful"